sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t albertombln/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true albertombln/react-test npm test -- --coverage

after_success:
  - docker build -t albertombln/multi-client ./client
  - docker build -t albertombln/multi-nginx ./nginx
  - docker build -t albertombln/multi-server ./server
  - docker build -t albertombln/multi-worker ./worker

  # Log in to the docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take those images and push them to docker hub
  - docker push albertombln/multi-client
  - docker push albertombln/multi-nginx
  - docker push albertombln/multi-server
  - docker push albertombln/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "eu-west-3"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-eu-west-3-640742193989"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
